# copy to ./kannon.properties (or ~/.config/kannon/kannon.properties)
bootstrap.servers=kafka.example.com:9095
security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-512
sasl.username=myuser
sasl.password=mypass
